### ISSUE TITLE
Make design decision on how to inform people about the Dataverse-DASH integration

### ISSUE THREAD

**Issue by qqmyers** [harvard-lts/dspace-angular#7]
per discussion around Miro board

**Comment by awoods** [comment]
Duplicate of: https://app.zenhub.com/workspaces/hdc-62163f60fb08c60011fa4795/issues/harvard-lts/hdc/49

**Comment by awoods** [comment]
@wwelling : Is this ticket not a duplicate?

**Comment by wwelling** [comment]
@awoods was not intentional to reopen this issue. Not really sure how it happened.
